### ISSUE TITLE
Typescript 변환

### ISSUE THREAD

**Issue by riroan** [Bootinfomap/frontend#39]
지금까지 한 것들 타입스크립트로 변환

1. 컴포넌트 확장자는 .tsx (app폴더, _config폴더는 ts)
2. 컴포넌트에 대응하는 props 타입이름은 '<컴포넌트이름>Props'로 한다. (예를들어 컴포넌트가 Map이면 props타입 이름은 MapProps)
3. import하고 사용하지 않는 아이템들 삭제

**Comment by riroan** [comment]
예제는 커밋 68d0595, a0b3708 확인해주세요.

**Comment by nayounsang** [comment]
명기님 각자 작성한 컴포넌트에 대해 type지정해주면 되려나요?
참고로 _types/navigationType에는 navigation(bottomtab제외)에대한 type을 작성했습니다

**Comment by riroan** [comment]
1. 네 각자 작성한 컴포넌트에만 지정해주세요.
2. 그냥 다 generalType에 넣어주세요.

**Comment by nayounsang** [comment]
넵 완료했습니다

**Comment by riroan** [comment]
1. NaverMapView는 이거 개발하신분이 타입지정을 잘못하신거 같긴 한데... 돌아는 가더라구요. 
2. 윤상님이 한거중에 타입이 <컴포넌트>Prop이랑 <컴포넌트>Props이게 있던데 둘이 나눈 이유가 있나요?
